---
kind: pipeline
name: default
type: docker


steps:
  - name: restore-cache
    image: drillster/drone-volume-cache
    settings:
      restore: true
      mount:
        - thehive-training/packer_cache
    volumes: [{name: cache, path: /cache}]

  - name: build
    image: thehiveproject/docker-vbox-packer
    privileged: true
    commands:
      - cd thehive-training
      - pwd
      - packer build ubuntu_core.json
      - packer build thehive-training_v4.json
      - cp output-thehive/thehive-training.ova /output/thehive-training-$${DRONE_BUILD_NUMBER}.ova
      - ln -fs thehive-training-$${DRONE_BUILD_NUMBER}.ova /output/thehive-training-latest.ova
    volumes: [{name: output, path: /output}]

  - name: save-cache
    image: drillster/drone-volume-cache
    settings:
      rebuild: true
      mount:
        - thehive-training/packer_cache
    volumes: [{name: cache, path: /cache}]

  - name: scp ova and sha256 files
    image: appleboy/drone-scp
    settings:
      host: {from_secret: package_host}
      username: {from_secret: package_user}
      key: {from_secret: package_key}
      target: {from_secret: package_path}
      source:
        - /output/thehive-training-${DRONE_BUILD_NUMBER}.ova
        - /output/thehive-training-latest.ova
        - thehive-training/packer_thehive_virtualbox-iso_sha256.checksum
      strip_components: 1
    volumes: [{name: output, path: /output}]

  - name: send message
    image: thehiveproject/drone_keybase
    settings:
      username: {from_secret: keybase_username}
      paperkey: {from_secret: keybase_paperkey}
      channel: {from_secret: keybase_channel}
    commands:
    - |
      keybase oneshot -u "$PLUGIN_USERNAME" --paperkey "$PLUGIN_PAPERKEY"
      URL="$DRONE_SYSTEM_PROTO://$DRONE_SYSTEM_HOST/$DRONE_REPO/$DRONE_BUILD_NUMBER"
      if [ $DRONE_BUILD_STATUS = "success" ]
      then
        keybase chat send "$PLUGIN_CHANNEL" ":white_check_mark: $DRONE_REPO: build succeeded $URL"
      else
        keybase chat send "$PLUGIN_CHANNEL" ":x: $DRONE_REPO: build failed $URL"
      fi
    when:
      status:
      - success
      - failure

volumes:
  - name: cache
    host: {path: /opt/drone/cache}
  - name: output
    host: {path: /opt/drone/output}
